# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-05-03 00:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Additional_Img',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_file', models.ImageField(upload_to='templates')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=245)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('b_fname', models.CharField(max_length=245)),
                ('b_lname', models.CharField(max_length=245)),
                ('b_address', models.TextField()),
                ('b_address2', models.TextField()),
                ('b_city', models.CharField(max_length=245)),
                ('b_state', models.CharField(max_length=2)),
                ('b_zip', models.IntegerField()),
                ('sh_fname', models.CharField(max_length=245)),
                ('sh_lname', models.CharField(max_length=245)),
                ('sh_address', models.TextField()),
                ('sh_address2', models.TextField()),
                ('sh_city', models.CharField(max_length=245)),
                ('sh_state', models.CharField(max_length=2)),
                ('sh_zip', models.IntegerField()),
                ('email', models.CharField(max_length=245)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Order_Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quant', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('belongs_to_shopper', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items_forthis_shopper', to='online_shopping.Order')),
            ],
        ),
        migrations.CreateModel(
            name='Prod',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=245)),
                ('desc', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('main_img', models.ImageField(upload_to='templates')),
                ('count', models.IntegerField()),
                ('sold', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prod_in_category', to='online_shopping.Category')),
            ],
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('progress', models.CharField(max_length=245)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name='order_item',
            name='includes_prod',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='included_in_order', to='online_shopping.Prod'),
        ),
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_label', to='online_shopping.Status'),
        ),
        migrations.AddField(
            model_name='additional_img',
            name='for_prod',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='more_img', to='online_shopping.Prod'),
        ),
    ]
