# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-06-07 18:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('online_shopping', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='additional_img',
            name='image_file',
            field=models.ImageField(upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='prod',
            name='main_img',
            field=models.ImageField(upload_to='images/'),
        ),
    ]
