# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-06-13 01:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('online_shopping', '0004_order_total_cost'),
    ]

    operations = [
        migrations.AddField(
            model_name='order_item',
            name='cost',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=8),
        ),
    ]
